### ISSUE TITLE
Extend documentation for end 2 end testing

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1420]
When you have no chrome you get the following error.
So we should add this requirement to the docs.

```
➜  Neos.Neos.Ui git:(master) ✗ yarn test:e2e
yarn run v1.3.2
$ yarn run testcafe -- chrome:headless Tests/IntegrationTests/* --selector-timeout=30000 --assertion-timeout=30000
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ /Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/.bin/testcafe chrome:headless Tests/IntegrationTests/contentModule.js Tests/IntegrationTests/pageModel.js --selector-timeout=30000 --assertion-timeout=30000
ERROR Was unable to open the browser "chrome:headless" due to error.

Error: Unable to run the browser. The browser path or command template is not specified.
    at checkBrowserPath$ (/Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/testcafe-browser-tools/lib/api/open.js:47:23)
    at tryCatch (/Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:146:20)
    at /Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:191:11
    at Promise.F (/Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/testcafe-browser-tools/node_modules/core-js/library/modules/$.export.js:30:36)
    at callInvokeWithMethodAndArg (/Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:190:16)
    at AsyncIterator.enqueue (/Users/markusgunther/Development/neos-development-distribution/Packages/Application/Neos.Neos.Ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:211:37)

Type "testcafe -h" for help.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by markusguenther** [comment]
Hehe @mstruebing was fast with tagging but already added that ;)
Just needed to create the issue first.
