### ISSUE TITLE
Missing dependency for ck5 editor packages when building backend components

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-ui#1978]
### Description

Building the YoastSEO info module from the package https://github.com/Sebobo/Shel.Neos.YoastSeo fails as `@ckeditor/ckeditor5-theme-lark` is shown as missing dependency.

It's used in the `webpack.config.js` but not required in `@neos-project/build-essentials`.

### Steps to Reproduce

Install the YoastSEO package and try running `yarn install` and `yarn build-all` in the folder `Packages/Plugins/Shel.Neos.YoastSeo/Resources/Private/Scripts/YoastInfoView`

#### Expected behavior

The build should run fine.

#### Actual behavior

```
$ npm run build-inspector && npm run build-app

> @ build-inspector /foo/bar/Packages/Plugins/Shel.Neos.YoastSeo/Resources/Private/Scripts/YoastInfoView
> neos-react-scripts build

module.js:549
    throw err;
    ^

Error: Cannot find module '@ckeditor/ckeditor5-theme-lark'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/foo/bar/Packages/Plugins/Shel.Neos.YoastSeo/Resources/Private/Scripts/YoastInfoView/node_modules/@neos-project/build-essentials/src/webpack.config.js:129:52)
    at Module._compile (module.js:652:30)

```

### Affected Versions

Neos: 4.0

UI: 1.2.1

**Comment by Sebobo** [comment]
OK thanks for testing @mstruebing . Could solve it by deleting all related packages, node_modules and whatever else... 
No clue what npm & yarn & friends are doing...
