### ISSUE TITLE
neos-react-scripts test

### ISSUE THREAD

**Issue by s-diez** [neos/neos-ui#2335]
### Description

While searching for possible "neos-react-scripts" commands I found the following case statement.
https://github.com/neos/neos-ui/blob/40355ebadf5cee9c122e5e71fb2d9010ee3a6764/packages/neos-ui-extensibility/bin/neos-react-scripts.js#L9
But there is no file `packages/neos-ui-extensibility/scripts/test.js`.

Was this planed and never implemented or was the script removed but the statement was missed?

### Steps to Reproduce

1. Create a new package.json
2. Require `@neos-project/neos-ui-extensibility`
3. Add `"test": "neos-react-scripts test"` to scripts in package.json
4.  Run `npm run test`

#### Expected behavior

Error message `Unknown script "test". Perhaps you need to update neos-react-scripts?` or running tests.

#### Actual behavior

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../scripts/test'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at Object.<anonymous> (SomePath/Resources/Private/CustomCkEditor/node_modules/@neos-project/neos-ui-extensibility/bin/neos-react-scripts.js:12:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

### Affected Versions

Neos: 4.2

UI: 3.0.2

Edit: Used template

**Comment by markusguenther** [comment]
Hi,

thanks for reporting.
As the code goes back to the very first commits it was never implemented I guess.

What do you think @dimaip ?
