### ISSUE TITLE
Error: open stream failed after setup step 3

### ISSUE THREAD

**Issue by ptr2null** [neos/neos-ui#2818]
### Description

In Neos Setup Step 3 we're asked to give some information about our site and site-package.
After that it throws a fatal error.

#### Actual behavior

```
Warning: Uncaught Neos\Flow\Error\Exception: Warning: require(C:/xampp/htdocs/ohm-xpcd/Data/Temporary/Development/Doctrine/Proxies\__CG__NeosContentRepositoryDomainModelNodeData.php): failed to open stream: No such file or directory in C:\xampp\htdocs\ohm-xpcd\Packages\Libraries\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php line 204 in C:\xampp\htdocs\ohm-xpcd\Packages\Framework\Neos.Flow\Classes\Error\ErrorHandler.php:81 Stack trace: #0 C:\xampp\htdocs\ohm-xpcd\Packages\Libraries\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php(204): Neos\Flow\Error\ErrorHandler->handleError(2, 'require(C:/xamp...', 'C:\\xampp\\htdocs...', 204, Array) #1 C:\xampp\htdocs\ohm-xpcd\Packages\Libraries\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php(204): require() #2 C:\xampp\htdocs\ohm-xpcd\Packages\Libraries\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php(114): Doctrine\Common\Proxy\AbstractProxyFactory->getProxyDefinition('Neos\\ContentRep...') #3 C:\xampp\ht in C:\xampp\htdocs\ohm-xpcd\Packages\Framework\Neos.Flow\Classes\Error\ErrorHandler.php on line 81

Fatal error: Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required 'C:/xampp/htdocs/ohm-xpcd/Data/Temporary/Development/Doctrine/Proxies\__CG__NeosContentRepositoryDomainModelNodeData.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\ohm-xpcd\Packages\Libraries\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php on line 204
```
### Affected Versions

Neos: 5.3.0 (installed with composer, latest version)
PHP: 7.3.23
UI: N/A

Is this a bug?

**Comment by markusguenther** [comment]
Hello @ptr2null ,

do you mean composer 2.x with composer latest?
We have released a new version of neos and flow some days ago to be composer compatible.

Would be nice to have more informations about which neos and flow you use in detail and the composer version :)
Thanks for reporting that.

**Comment by ptr2null** [comment]
Hello Markus,

I'll post you the version list of composer and – with "composer show" – the installed package versions:

Composer version 2.0.4 2020-10-30 22:39:11

````
behat/transliterator                 v1.3.0             String transliterator
composer/ca-bundle                   1.2.8              Lets you find a path to the system CA bundle, and includ...
composer/composer                    1.10.17            Composer helps you declare, manage and install dependenc...
composer/package-versions-deprecated 1.11.99            Composer plugin that provides efficient querying for ins...
composer/semver                      1.7.1              Semver library that offers utilities, version constraint...
composer/spdx-licenses               1.5.4              SPDX licenses list and validation library.
composer/xdebug-handler              1.4.4              Restarts a process without Xdebug.
doctrine/annotations                 1.11.1             Docblock Annotations Parser
doctrine/cache                       1.10.2             PHP Doctrine Cache library is a popular cache implementa...
doctrine/collections                 1.6.7              PHP Doctrine Collections library that adds additional fu...
doctrine/common                      2.13.3             PHP Doctrine Common project is a library that provides a...
doctrine/dbal                        2.12.0             Powerful PHP database abstraction layer (DBAL) with many...
doctrine/event-manager               1.1.1              The Doctrine Event Manager is a simple PHP event system ...
doctrine/inflector                   1.4.3              PHP Doctrine Inflector is a small library that can perfo...
doctrine/instantiator                1.3.1              A small, lightweight utility to instantiate objects in P...
doctrine/lexer                       1.2.1              PHP Doctrine Lexer parser library that can be used in To...
doctrine/migrations                  v1.8.1             Database Schema migrations using Doctrine DBAL
doctrine/orm                         2.7.4              Object-Relational-Mapper for PHP
doctrine/persistence                 1.3.8              The Doctrine Persistence project is a set of shared inte...
doctrine/reflection                  1.2.2              The Doctrine Reflection project is a simple library used...
flowpack/neos-frontendlogin          4.0.0              Neos plugin demonstrating a simple frontend login
gedmo/doctrine-extensions            v2.4.42            Doctrine2 behavioral extensions
guzzlehttp/psr7                      1.7.0              PSR-7 message implementation that also provides common u...
imagine/imagine                      1.2.3              Image processing for PHP 5.3
justinrainbow/json-schema            5.2.10             A library to validate a json schema.
league/csv                           9.6.1              CSV data manipulation made easy in PHP
mikey179/vfsstream                   v1.6.8             Virtual file system to mock the real file system in unit...
myclabs/deep-copy                    1.10.1             Create deep copies (clones) of your objects
neos/behat                           dev-master 33c186a Behat support package for Neos Flow
neos/buildessentials                 dev-master a7cb879 Neos Flow Build Toolchain Essentials
neos/cache                           6.3.3              Neos Cache Framework
neos/composer-plugin                 2.1.0              Flow Composer Plugin
neos/content-repository              5.3.0              Content repository based on Flow, specifically made for ...
neos/demo                            6.2.0              Site package for the Neos Demo Site
neos/diff                            5.3.0              This is a comprehensive library for generating differenc...
neos/eel                             6.3.3              The Embedded Expression Language (Eel) is a building blo...
neos/error-messages                  6.3.3              Flow error messages
neos/flow                            6.3.3              Flow Application Framework
neos/flow-log                        6.3.3              Flow Framework Logger
neos/fluid-adaptor                   6.3.3              Fluid Templating Framework Adaptor
neos/form                            5.2.0              Extensible and flexible API for building web forms
neos/fusion                          5.3.0              Fusion is a hierarchical, prototype based processing lan...
neos/fusion-afx                      v1.4.1             JSX inspired compact syntax for Neos.Fusion
neos/fusion-form                     v1.0.3             Fusion Form
neos/http-factories                  6.3.3              PSR-17 HTTP Factories
neos/imagine                         3.1.2             
neos/kickstarter                     6.3.3              A simple generator for controller and views.
neos/media                           5.3.0              The Media package
neos/media-browser                   5.3.0              This module allows managing of media assets including pi...
neos/neos                            5.3.0              An open source Content Application Platform based on Flo...
neos/neos-setup                      1.0.2              Custom neos/setup steps and configuration for Neos CMS
neos/neos-ui                         5.3.4              Neos CMS UI written in React
neos/neos-ui-compiled                5.3.4             
neos/nodetypes-assetlist             5.3.0              A simple asset list node type.
neos/nodetypes-basemixins            5.3.0              Base mixins which are useful across projects.
neos/nodetypes-contentreferences     5.3.0              A simple content reference node type.
neos/nodetypes-form                  5.3.0              A simple form node type.
neos/nodetypes-html                  5.3.0              A simple html node type.
neos/nodetypes-navigation            5.3.0              A navigation node type.
neos/party                           5.0.2              A party package for PHP based on the OASIS Customer Info...
neos/redirecthandler                 4.0.3              Basic API to handle HTTP redirects with the Flow Framework
neos/redirecthandler-databasestorage 4.1.0              A plugin for neos/redirecthandler to store redirects in ...
neos/redirecthandler-neosadapter     4.1.0              Neos Redirect Handler
neos/redirecthandler-ui              2.3.0              This package provides a backend module to manage Neos.Re...
neos/seo                             3.1.1              SEO configuration and tools for Neos
neos/setup                           4.1.1              An extensible setup tool for Neos Flow based applications
neos/site-kickstarter                5.3.0              A simple generator for Neos assets, like sites and plugins.
neos/twitter-bootstrap               3.0.5              Simple and flexible HTML, CSS, and Javascript for popula...
neos/utility-arrays                  6.3.3              Flow Array Utilities
neos/utility-files                   6.3.3              Flow Files Utilities
neos/utility-mediatypes              6.3.3              Flow Media Types Utilities
neos/utility-objecthandling          6.3.3              Flow array/object property and type utilities
neos/utility-opcodecache             6.3.3              Flow Opcode Cache Utilities
neos/utility-pdo                     6.3.3              Flow PDO Utilities
neos/utility-schema                  6.3.3              Flow Schema Utilities
neos/utility-unicode                 6.3.3              Flow Unicode Utilities
ocramius/proxy-manager               2.2.3              A library providing utilities to generate, instantiate a...
paragonie/random_compat              v9.99.99           PHP 5.x polyfill for random_bytes() and random_int() fro...
phar-io/manifest                     1.0.3              Component for reading phar.io manifest information from ...
phar-io/version                      2.0.1              Library for handling version information and constraints
phpdocumentor/reflection-common      2.2.0              Common reflection classes used by phpdocumentor to refle...
phpdocumentor/reflection-docblock    5.2.2              With this component, a library can provide support for a...
phpdocumentor/type-resolver          1.4.0              A PSR-5 based resolver of Class names, Types and Structu...
phpspec/prophecy                     1.12.1             Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage            7.0.10             Library that provides collection, processing, and render...
phpunit/php-file-iterator            2.0.2              FilterIterator implementation that filters files based o...
phpunit/php-text-template            1.2.1              Simple template engine.
phpunit/php-timer                    2.1.2              Utility class for timing
phpunit/php-token-stream             3.1.1              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                      8.5.8              The PHP Unit Testing framework.
psr/cache                            1.0.1              Common interface for caching libraries
psr/container                        1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-factory                     1.0.1              Common interfaces for PSR-7 HTTP message factories
psr/http-message                     1.0.1              Common interface for HTTP messages
psr/http-server-handler              1.0.1              Common interface for HTTP server-side request handler
psr/http-server-middleware           1.0.1              Common interface for HTTP server-side middleware
psr/log                              1.1.3              Common interface for logging libraries
psr/simple-cache                     1.0.1              Common interfaces for simple caching
ralouphie/getallheaders              3.0.3              A polyfill for getallheaders.
ramsey/uuid                          3.9.3              Formerly rhumsaa/uuid. A PHP 5.4+ library for generating...
sebastian/code-unit-reverse-lookup   1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                 3.0.2              Provides the functionality to compare PHP values for equ...
sebastian/diff                       3.0.2              Diff implementation
sebastian/environment                4.2.3              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   3.1.2              Provides the functionality to export PHP variables for v...
sebastian/global-state               3.0.0              Snapshotting of global state
sebastian/object-enumerator          3.0.3              Traverses array structures and object graphs to enumerat...
sebastian/object-reflector           1.1.1              Allows reflection of object attributes, including inheri...
sebastian/recursion-context          3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations        2.0.1              Provides a list of PHP built-in functions that operate o...
sebastian/type                       1.1.3              Collection of value objects that represent the types of ...
sebastian/version                    2.0.1              Library that helps with managing the version number of G...
seld/jsonlint                        1.8.2              JSON Linter
seld/phar-utils                      1.1.1              PHAR file format utilities, for when PHP phars you up
symfony/console                      v4.4.16            Symfony Console Component
symfony/css-selector                 v2.8.52            Symfony CssSelector Component
symfony/dom-crawler                  v4.4.16            Symfony DomCrawler Component
symfony/filesystem                   v5.1.8             Symfony Filesystem Component
symfony/finder                       v5.1.8             Symfony Finder Component
symfony/polyfill-ctype               v1.20.0            Symfony polyfill for ctype functions
symfony/polyfill-mbstring            v1.20.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php73               v1.20.0            Symfony polyfill backporting some PHP 7.3+ features to l...
symfony/polyfill-php80               v1.20.0            Symfony polyfill backporting some PHP 8.0+ features to l...
symfony/process                      v5.1.8             Symfony Process Component
symfony/service-contracts            v2.2.0             Generic abstractions related to writing services
symfony/yaml                         v4.4.16            Symfony Yaml Component
theseer/tokenizer                    1.2.0              A small library for converting tokenized PHP source code...
typo3fluid/fluid                     2.6.9              The TYPO3 Fluid template rendering engine
webmozart/assert                     1.9.1              Assertions to validate method input/output with nice err...
zendframework/zend-code              3.4.1              Extensions to the PHP Reflection API, static code scanni...
zendframework/zend-eventmanager      3.2.1              Trigger and listen to events within a PHP application
````

Hope that helps
Markus

**Comment by grebaldi** [comment]
Sorry for the late response @ptr2null.

Is this actually UI-related? You say:

> In Neos Setup Step 3 [...]

If an error is happening while using the Neos.Setup GUI Tool, the issue might be better addressed at: https://github.com/neos/setup/issues

The error message looks like a more low-level problem that's probably related to your Windows Setup. Would you mind creating a Post on https://discuss.neos.io/ for this? It is more likely you will get help there from people with more experience in that particular area.
