### ISSUE TITLE
Neos backend crashes with "TypeError: _ is not a function"

### ISSUE THREAD

**Issue by simonschaufi** [neos/neos-ui#3092]
### Description

When I click in the inspector on the "Stats" icon, then the whole neos backend crashes with the error: 

```
react-dom.production.min.js:209 TypeError: _ is not a function
    at Function.ye.ticks (time.js:49:12)
    at TimeSeriesView.j.getXTicks (index.js:114:29)
    at TimeSeriesView.render (index.js:139:29)
    at gi (react-dom.production.min.js:182:192)
    at fi (react-dom.production.min.js:181:224)
    at So (react-dom.production.min.js:263:490)
    at Qj (react-dom.production.min.js:246:265)
    at Kj (react-dom.production.min.js:246:194)
    at yj (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
time.js:49 Uncaught (in promise) TypeError: _ is not a function
    at Function.ye.ticks (time.js:49:12)
    at TimeSeriesView.j.getXTicks (index.js:114:29)
    at TimeSeriesView.render (index.js:139:29)
    at gi (react-dom.production.min.js:182:192)
    at fi (react-dom.production.min.js:181:224)
    at So (react-dom.production.min.js:263:490)
    at Qj (react-dom.production.min.js:246:265)
    at Kj (react-dom.production.min.js:246:194)
    at yj (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
```

### Steps to Reproduce

1. Install https://github.com/Flowpack/neos-matomo and set it up
2. Click on the home page
3. Click in the inspector on the "Stats" icon

#### Expected behavior

See the stats

#### Actual behavior

White screen, the whole backend disappears

![chrome-capture-2022-2-24](https://user-images.githubusercontent.com/941794/160016891-8ac7f250-ab41-40be-9674-c1b9382c7890.gif)

### Affected Versions

Neos: v7.3.2

UI: v7.3.3

Neos Matomo 3.4.0

**Comment by pKallert** [comment]
This also happens with the Neos Googleanalytics Plugin: https://github.com/neos/neos-googleanalytics

**Comment by paavo** [comment]
Did anyone found a fix for this yet?

**Comment by paavo** [comment]
**Affected Versions**
Neos: v5.3.9
UI: v5.3.15
neos/googleanalytics: 3.2.5

**Comment by mhsdesign** [comment]
will look into it. seems by the gif that something is crashing after 'loading' (below visits per day) has finished...

**Comment by simonschaufi** [comment]
Fixed
