### ISSUE TITLE
BUG: Typescript Ui plugin with `@neos-project/react-ui-components@8.3.0-beta2`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3400]
WIP

```
    "@neos-project/neos-ui-extensibility-webpack-adapter": "8.3.0-beta2",
    "@neos-project/react-ui-components": "8.3.0-beta2",
```

when installing the old 5.3.13 react-ui-components typescript works in the webpack-adapter build...
it seems to be related to the package.json of react-ui-components. If i remove here the `types` field it works again.

```
ModuleBuildError: Module build failed (from /My.Ui.Plugin/node_modules/ts-loader/index.js):
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:43500:18)
    at /My.Ui.Plugin/node_modules/ts-loader/dist/servicesHost.js:373:77
    at /My.Ui.Plugin/node_modules/ts-loader/dist/servicesHost.js:95:142
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/My.Ui.Plugin/node_modules/ts-loader/dist/servicesHost.js:95:125)
    at actualResolveTypeReferenceDirectiveNamesWorker (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:119382:163)
    at resolveTypeReferenceDirectiveNamesWorker (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:119682:26)
    at processTypeReferenceDirectives (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:121185:31)
    at findSourceFileWorker (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:121070:21)
    at findSourceFile (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:120922:26)
    at /My.Ui.Plugin/node_modules/webpack/lib/NormalModule.js:316:20
    at /My.Ui.Plugin/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /My.Ui.Plugin/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/My.Ui.Plugin/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/My.Ui.Plugin/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/My.Ui.Plugin/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/My.Ui.Plugin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /My.Ui.Plugin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /My.Ui.Plugin/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) 0 [
  ModuleBuildError: Module build failed (from /My.Ui.Plugin/node_modules/ts-loader/index.js):
  Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
      at Object.resolveTypeReferenceDirective (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:43500:18)
      at /My.Ui.Plugin/node_modules/ts-loader/dist/servicesHost.js:373:77
      at /My.Ui.Plugin/node_modules/ts-loader/dist/servicesHost.js:95:142
      at Array.map (<anonymous>)
      at Object.resolveTypeReferenceDirectives (/My.Ui.Plugin/node_modules/ts-loader/dist/servicesHost.js:95:125)
      at actualResolveTypeReferenceDirectiveNamesWorker (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:119382:163)
      at resolveTypeReferenceDirectiveNamesWorker (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:119682:26)
      at processTypeReferenceDirectives (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:121185:31)
      at findSourceFileWorker (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:121070:21)
      at findSourceFile (/My.Ui.Plugin/node_modules/typescript/lib/typescript.js:120922:26)
      at /My.Ui.Plugin/node_modules/webpack/lib/NormalModule.js:316:20
      at /My.Ui.Plugin/node_modules/loader-runner/lib/LoaderRunner.js:367:11
      at /My.Ui.Plugin/node_modules/loader-runner/lib/LoaderRunner.js:233:18
      at runSyncOrAsync (/My.Ui.Plugin/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
      at iterateNormalLoaders (/My.Ui.Plugin/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
      at Array.<anonymous> (/My.Ui.Plugin/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
      at Storage.finished (/My.Ui.Plugin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
      at /My.Ui.Plugin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
      at /My.Ui.Plugin/node_modules/graceful-fs/graceful-fs.js:123:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by mhsdesign** [comment]
@Sebobo reported this problem also in older versions, so might not  related to my major changes

**Comment by grebaldi** [comment]
8.3 had been released. Is this still an issue, @mhsdesign?

**Comment by mhsdesign** [comment]
we encountered no further issues so far
